### ISSUE TITLE
Are you aware of Mapilliary?

### ISSUE THREAD

**Issue by chriskbach** [unsurv/unsurv-android#1]
Are you aware of [Mapilliary](https://www.mapillary.com/) ?

The idea of driving around with a scooter or bike and a 360° camera on a helmet, which you mentioned in your RC3 talk reminded me of Mapilliary. There you find a huge number of picture even from streets in Germany!

Have you considered this for your project?

**Comment by unsurv** [comment]
Sorry I missed the issues here on GitHub, someone on Twitter mentioned Mapillary too, even that they now include a surveillance camera detection. Thank you too for the tip. I will try to get access to that data and import it to OSM.

**Comment by chriskbach** [comment]
Great that people have similar ideas and interests
